service: conversations

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/conversations

package:
  exclude:
    - ./**
    - '!node_modules/**'
  include:
    - src/**
    - environment/**
    - schemas/**

functions:
  conversations_api:
    handler: src/conversations/adapters/conversations-http-lambda-adapter.handle
    description: Facilitate collaborative conversation editing between Alice and Bob.
    memorySize: 128
    timeout: 30
    reservedConcurrency: 10
    events:
      - http:
          path: mutations # add a mutation
          method: POST
      - http:
          path: conversations/{id} # find conversation details by id
          method: GET
          cors: true
      - http:
          path: conversations # find conversations
          method: GET
          cors: true
      - http:
          path: conversations/{id} # remove conversation
          method: DELETE
          cors: true

resources:
  Resources:
    ConversationsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: conversations
        AttributeDefinitions:
          - AttributeName: "conversationId"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "conversationId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
